name: Run Cypress Tests

on:
  push:
    branches:
      - main # Adjust based on your main branch
  pull_request:
    branches:
      - main # Trigger on PR to master branch

jobs:
  cypress-run:
    runs-on: ubuntu-latest # You can use macOS or Windows, depending on your environment

    steps:
      - name: cypressTesting repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22" # Node.js version for your project

      - name: Install dependencies
        working-directory: ./couse/Software-testing # Correct path to package.json
        run: npm install

      - name: Run Cypress tests
        working-directory: ./couse/Software-testing # Correct path to package.json
        run: npx cypress run # Or use `npx cypress open` for interactive mode
